image: Visual Studio 2017

install:
  - nuget restore
  - mkdir PlayspaceMover\third-party
  - git clone https://github.com/ValveSoftware/openvr PlayspaceMover\third-party\openvr
  - git clone https://github.com/matzman666/OpenVR-InputEmulator.git PlayspaceMover\third-party\OpenVR-InputEmulator

build_script:
  - msbuild PlayspaceMover.sln
#  - msbuild PlayspaceMover.sln /p:VisualStudioVersion=11.0

#artifacts:
#  - path: code_pages.exe
#  - path: code_pages_result.log
