image: Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Release

install:
  - nuget restore
  - mkdir PlayspaceMover\third-party
  - git clone --depth 1 https://github.com/ValveSoftware/openvr PlayspaceMover\third-party\openvr
  - git clone --depth 1 --branch 0.9.9-a2 https://github.com/g-truc/glm PlayspaceMover\third-party\glm-0.9.9-a2
  # TODO: Should add `branch=master` but it isn't on master yet.
  - appveyor DownloadFile "https://ci.appveyor.com/api/projects/trejkaz/OpenVR-InputEmulator/artifacts/LibVRInputEmulator-%CONFIGURATION%.zip?job=Configuration%%%%3A+%CONFIGURATION%"
  - 7z x LibVRInputEmulator-%CONFIGURATION%.zip -oPlayspaceMover\third-party\VRInputEmulator -r

build_script:
  - msbuild /P:Configuration=%CONFIGURATION% /P:Platform=%PLATFORM% PlayspaceMover.sln
  - dir /s PlayspaceMover\

#artifacts:
#  - path: code_pages.exe
#  - path: code_pages_result.log
