image: Visual Studio 2017

install:
  - nuget restore
  - cd PlayspaceMover
  - mkdir third-party
  - cd third-party
  - git clone https://github.com/ValveSoftware/openvr

#build_script:
#  - msbuild PlayspaceMover.sln
#  - msbuild PlayspaceMover.sln /p:VisualStudioVersion=11.0

#artifacts:
#  - path: code_pages.exe
#  - path: code_pages_result.log
