image: Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Release

install:
  - nuget restore
  - mkdir PlayspaceMover\third-party
  - git clone --depth 1 https://github.com/ValveSoftware/openvr PlayspaceMover\third-party\openvr
  - git clone --depth 1 https://github.com/matzman666/OpenVR-InputEmulator.git PlayspaceMover\third-party\OpenVR-InputEmulator
  # TODO: Should add `branch=master` but it isn't on master yet.
  - curl -fS -o LibVRInputEmulator.zip "https://ci.appveyor.com/api/projects/trejkaz/OpenVR-InputEmulator/artifacts/lib_vrinputemulator/Release/LibVRInputEmulator.zip?job=Configuration%%3A+%CONFIGURATION%"
  - 7z x LibVRInputEmulator.zip -othird-party\VRInputEmulator -r

build_script:
  - msbuild /P:Configuration=%CONFIGURATION% /P:Platform=%PLATFORM% PlayspaceMover.sln

#artifacts:
#  - path: code_pages.exe
#  - path: code_pages_result.log
