image: Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Release

install:
  - nuget restore
  - mkdir PlayspaceMover\third-party
  - git clone --depth 1 https://github.com/ValveSoftware/openvr PlayspaceMover\third-party\openvr
  # TODO: Should add `branch=master` but it isn't on master yet.
  - appveyor DownloadFile "https://ci.appveyor.com/api/projects/trejkaz/OpenVR-InputEmulator/artifacts/lib_vrinputemulator/%CONFIGURATION%/LibVRInputEmulator.zip?job=Configuration%%%%3A+%CONFIGURATION%"
  - 7z x LibVRInputEmulator.zip -oPlayspaceMover\third-party\VRInputEmulator -r
  - dir /s PlayspaceMover\third-party\VRInputEmulator

build_script:
  - msbuild /P:Configuration=%CONFIGURATION% /P:Platform=%PLATFORM% PlayspaceMover.sln

#artifacts:
#  - path: code_pages.exe
#  - path: code_pages_result.log
