image: Visual Studio 2017

#install:
#  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

before_build:
  - nuget restore

#build_script:
#  - msbuild PlayspaceMover.sln
#  - msbuild PlayspaceMover.sln /p:VisualStudioVersion=11.0


#artifacts:
#  - path: code_pages.exe
#  - path: code_pages_result.log
