image: Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Release

install:
  - nuget restore
  - mkdir PlayspaceMover\third-party

  # OpenVR
  - appveyor DownloadFile https://github.com/ValveSoftware/openvr/archive/v1.0.15.zip -FileName openvr-1.0.15.zip
  - 7z x openvr-1.0.15.zip -oPlayspaceMover\third-party
  - move PlayspaceMover\third-party\openvr-1.0.15 PlayspaceMover\third-party\openvr

  # GLM
  - appveyor DownloadFile https://github.com/g-truc/glm/archive/0.9.9-a2.zip -FileName glm-0.9.9-a2.zip
  - 7z x glm-0.9.9-a2.zip -oPlayspaceMover\third-party

  # OpenVR Input Emulator
  - appveyor DownloadFile https://github.com/matzman666/OpenVR-InputEmulator/archive/v1.3.zip -FileName OpenVR-InputEmulator-1.3.zip
  - 7z x OpenVR-InputEmulator-1.3.zip -oPlayspaceMover\third-party
  - move PlayspaceMover\third-party\OpenVR-InputEmulator-1.3 PlayspaceMover\third-party\OpenVR-InputEmulator
  - cd PlayspaceMover\third-party\OpenVR-InputEmulator
  - nuget install boost
  - nuget install boost-vc141
  - msbuild /P:Configuration=%CONFIGURATION% /P:Platform=%PLATFORM% /P:BOOST_ROOT=%BOOST_ROOT% /P:BOOST_LIB=%BOOST_LIB% /P:QTDIR=%QTDIR% 
      lib_vrinputemulator\lib_vrinputemulator.vcxproj
  - cd ..

  # TODO: Should add `branch=master` but it isn't on master yet.
  # - appveyor DownloadFile "https://ci.appveyor.com/api/projects/trejkaz/OpenVR-InputEmulator/artifacts/LibVRInputEmulator-%CONFIGURATION%.zip?job=Configuration%%%%3A+%CONFIGURATION%"
  # - 7z x LibVRInputEmulator-%CONFIGURATION%.zip -oPlayspaceMover\third-party\VRInputEmulator -r

build_script:
  - msbuild /P:Configuration=%CONFIGURATION% /P:Platform=%PLATFORM% PlayspaceMover.sln
  - dir /s PlayspaceMover\

#artifacts:
#  - path: code_pages.exe
#  - path: code_pages_result.log
